### ISSUE TITLE
Algo Shell Sort in Java

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#112]

**Comment by sowmyasri-Z** [comment]
could you please assign this to me

**Comment by Abishethvarman** [comment]
You have experience in our code base. right? 
So act accordingly @sowmyasri-Z. And dont forget to star this repo

**Comment by sowmyasri-Z** [comment]
okay!

**Comment by sowmyasri-Z** [comment]
may i know if this will be included in hactoberfest..

**Comment by Sakshipakhale11** [comment]
Hello ,I would like to work on this issue. Can you please assign it to me?

**Comment by Abishethvarman** [comment]
> Hello ,I would like to work on this issue. Can you please assign it to me?

This issue has assigned. Try unassigned issues
