### ISSUE TITLE
Algo Bubble Sort in C programming

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#44]
Need to make a readme file which should have the

Definition
Explanation in simple terms
Code related explanation.

**Comment by sowmyasri-Z** [comment]
can you please assign me this issue

**Comment by Abishethvarman** [comment]
go ahead. @sowmyasri-Z

**Comment by sowmyasri-Z** [comment]
you haven't assigned me this .can you please check?

**Comment by Abishethvarman** [comment]
> you haven't assigned me this .can you please check?

done

**Comment by sakshipatil4403** [comment]
@Abishethvarman can you please assign me this issue as i have already started working on it

**Comment by Abishethvarman** [comment]
@sakshipatil4403 start working on it. No progress from @sowmyasri-Z
