### ISSUE TITLE
Algo Bubble Sort in JavaScript

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#46]
Need to make a readme file which should have the

Definition
Explanation in simple terms
Code related explanation.

**Comment by suraakhila1** [comment]
please assign this issue to me

**Comment by sakshipatil4403** [comment]
Please assign this issue to me as I've already begun working on this issue.

**Comment by sakshipatil4403** [comment]
@Abishethvarman  please assign this issue to me as I've already begun working on this issue.

**Comment by Abishethvarman** [comment]
@sakshipatil4403 carry on

**Comment by Vybhavigithub** [comment]
@Abishethvarman I would like to provide documentation for this issue . Could you please assign

**Comment by Abishethvarman** [comment]
> @Abishethvarman I would like to provide documentation for this issue . Could you please assign

I appreciate your enthusiasm. but this issue has assigned to someone else. Try new algorithm which is not addressed and make PR.
