### ISSUE TITLE
Algo Selection Sort in JavaScript

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#50]
Need to make a readme file which should have the

Definition
Explanation in simple terms
Code related explanation.

**Comment by Abishethvarman** [comment]
@suraakhila1 taken. try in the linear search in the issue

**Comment by suraakhila1** [comment]
ok sir

**Comment by pranav-kale-01** [comment]
Is someone working on this issue or is the issue open to work on?
