### ISSUE TITLE
Algo Selection Sort in Python

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#51]
Need to make a readme file which should have the

Definition
Explanation in simple terms
Code related explanation.

**Comment by Subhashini014** [comment]
Could you please assign me this issue.

**Comment by Abishethvarman** [comment]
This issue was taken. @Subhashini014

**Comment by Subhashini014** [comment]
Ok I am working on this issue .Thank you for assigning me.
