### ISSUE TITLE
Algo Insertion Sort in C programming

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#52]
Need to make a readme file which should have the

Definition
Explanation in simple terms
Code related explanation.

**Comment by suraakhila1** [comment]
please assign this issue to me sir.

**Comment by Abishethvarman** [comment]
go ahead @suraakhila1

**Comment by GILBERTKETER** [comment]
can i do this sir?

**Comment by Abishethvarman** [comment]
No progress from @suraakhila1  so you can carry on @GILBERTKETER
