### ISSUE TITLE
Algo Linear Search in Java 

### ISSUE THREAD

**Issue by Abishethvarman** [Abishethvarman/programming-resources#78]

**Comment by sowmyasri-Z** [comment]
can you please assign me this issue?

**Comment by Abishethvarman** [comment]
> can you please assign me this issue?

Assigned

**Comment by sowmyasri-Z** [comment]
can you please let me know is issue will be included in hacktoberfest?

**Comment by Abishethvarman** [comment]
Once your PR merged, you can check check it in the hacktoberfest.com
